### ISSUE TITLE
GLTF2 export crashing Goxel

### ISSUE THREAD

**Issue by unfa** [guillaumechereau/goxel#213]
I'ma new Goxel user, today I've made a sightly more complex project than what I've done before, and it fails to export into GLFT2.

Goxel crashes every time I export to GLTF2, producing no file or any info in CMD on Windows 10.

I haven't yet tried exporting the same project under Linux.

The only workaround I managed was to use Magica Voxel. The file exports well to it's format, where I can convert it to OBJ, and Magica Voxel exports textures as well.

I am using Goxel however because I'm seeking libre software tools for everything I do.

Does anybody else have similar issues?

Here's a test project I can reproduce this with:
[CrashTest.zip](https://github.com/guillaumechereau/goxel/files/5385338/CrashTest.zip)

I've used alpha 0.5 while painting and also anti-aliased brush - maybe this is causing problems when generating the palette texture?

**Comment by guillaumechereau** [comment]
Could you send me a gox file that I could try to see if I can reproduce the bug?

**Comment by guillaumechereau** [comment]
I can reproduce the crash.  I'll have a look at it.

**Comment by guillaumechereau** [comment]
I fixed the bug in master.

**Comment by ajjaic** [comment]
If this is fixed, would you want to keep this issue still open? I think it might be better to close. By the way, thanks for goxel. Lovely piece of software. I love it for its in-editor programming feature

**Comment by guillaumechereau** [comment]
Yes I'll close it for now.  Thanks!

**Comment by JasperMoerland** [comment]
I still have this issue this is the error report I get -------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               goxel [4632]
Path:                  /Applications/goxel.app/Contents/MacOS/goxel
Identifier:            com.noctuasoftware.goxel
Version:               0.11.0 (7)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-01-04 17:31:55.1142 +0100
OS Version:            macOS 13.6.1 (22G313)
Report Version:        12
Anonymous UUID:        42C6F70A-C4A9-D0A6-7443-B33C6002CDB8

Sleep/Wake UUID:       4E52C856-3F20-4130-ABCD-210F19769DB2

Time Awake Since Boot: 44000 seconds
Time Since Wake:       850 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   goxel [4632]

Application Specific Information:
abort() called


Kernel Triage:
VM - (arg = 0x0) pmap_enter retried due to resource shortage
VM - (arg = 0x0) pmap_enter retried due to resource shortage
VM - (arg = 0x0) pmap_enter retried due to resource shortage
VM - (arg = 0x0) pmap_enter retried due to resource shortage
VM - (arg = 0x0) pmap_enter retried due to resource shortage


Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x194ee0744 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x194f17c28 pthread_kill + 288
2   libsystem_c.dylib             	       0x194e25ae8 abort + 180
3   libswiftCore.dylib            	       0x1a3fcbad8 swift::fatalErrorv(unsigned int, char const*, char*) + 136
4   libswiftCore.dylib            	       0x1a3fcbaf8 swift::fatalError(unsigned int, char const*, ...) + 32
5   libswiftCore.dylib            	       0x1a3fcc108 swift::runtime::AccessSet::insert(swift::runtime::Access*, void*, void*, swift::ExclusivityFlags) + 536
6   libswiftCore.dylib            	       0x1a3fcc16c swift_beginAccess + 84
7   goxel                         	       0x1024cc450 0x102358000 + 1524816
8   goxel                         	       0x1024cc840 0x102358000 + 1525824
9   AppKit                        	       0x198a66f94 _routeMouseMovedEvent + 276
10  AppKit                        	       0x198348b70 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 432
11  AppKit                        	       0x1983487ec -[NSWindow(NSEventRouting) sendEvent:] + 284
12  AppKit                        	       0x1988be600 routeMouseMovedEvent + 312
13  AppKit                        	       0x198347968 -[NSApplication(NSEvent) sendEvent:] + 1100
14  goxel                         	       0x1024cc0ec 0x102358000 + 1523948
15  goxel                         	       0x1024cc170 0x102358000 + 1524080
16  AppKit                        	       0x198453c0c -[NSApplication _doModalLoop:peek:] + 276
17  AppKit                        	       0x198452ad4 __35-[NSApplication runModalForWindow:]_block_invoke_2 + 56
18  AppKit                        	       0x198452a80 __35-[NSApplication runModalForWindow:]_block_invoke + 108
19  AppKit                        	       0x198452364 _NSTryRunModal + 100
20  AppKit                        	       0x198452224 -[NSApplication runModalForWindow:] + 292
21  AppKit                        	       0x198b6c6b8 -[NSSavePanel runModal] + 340
22  goxel                         	       0x102395a50 0x102358000 + 252496
23  goxel                         	       0x102476c9c 0x102358000 + 1174684
24  goxel                         	       0x1024c532c 0x102358000 + 1495852
25  goxel                         	       0x10237737c 0x102358000 + 127868
26  goxel                         	       0x10247b2e0 0x102358000 + 1192672
27  goxel                         	       0x10247e6ac 0x102358000 + 1205932
28  goxel                         	       0x102471d28 0x102358000 + 1154344
29  goxel                         	       0x10247ace0 0x102358000 + 1191136
30  goxel                         	       0x1024752e0 0x102358000 + 1168096
31  goxel                         	       0x1024d0824 0x102358000 + 1542180
32  goxel                         	       0x1024cd294 0x102358000 + 1528468
33  Foundation                    	       0x195fa63f8 __NSFireTimer + 104
34  CoreFoundation                	       0x195010338 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
35  CoreFoundation                	       0x19500ffe0 __CFRunLoopDoTimer + 940
36  CoreFoundation                	       0x19500fb38 __CFRunLoopDoTimers + 356
37  CoreFoundation                	       0x194ff52b8 __CFRunLoopRun + 1852
38  CoreFoundation                	       0x194ff4428 CFRunLoopRunSpecific + 612
39  HIToolbox                     	       0x19e846df0 RunCurrentEventLoopInMode + 292
40  HIToolbox                     	       0x19e846c2c ReceiveNextEventCommon + 648
41  HIToolbox                     	       0x19e846984 _BlockUntilNextEventMatchingListInModeWithFilter + 76
42  AppKit                        	       0x19821b97c _DPSNextEvent + 636
43  AppKit                        	       0x19821ab18 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 716
44  AppKit                        	       0x19820ef7c -[NSApplication run] + 464
45  AppKit                        	       0x1981e63cc NSApplicationMain + 880
46  goxel                         	       0x1024cd414 0x102358000 + 1528852
47  dyld                          	       0x194bbff28 start + 2236

Thread 1:
0   libsystem_pthread.dylib       	       0x194f12d8c start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x194f12d8c start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x194f12d8c start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	       0x194f12d8c start_wqthread + 0

Thread 5:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x194ed7f34 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x194eea260 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x194ee0b98 mach_msg_overwrite + 604
3   libsystem_kernel.dylib        	       0x194ed82b0 mach_msg + 24
4   CoreFoundation                	       0x194ff6754 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x194ff5034 __CFRunLoopRun + 1208
6   CoreFoundation                	       0x194ff4428 CFRunLoopRunSpecific + 612
7   AppKit                        	       0x198345f54 _NSEventThread + 172
8   libsystem_pthread.dylib       	       0x194f17fa8 _pthread_start + 148
9   libsystem_pthread.dylib       	       0x194f12da0 thread_start + 8

Thread 6:
0   libsystem_pthread.dylib       	       0x194f12d8c start_wqthread + 0

Thread 7:
0   libsystem_pthread.dylib       	       0x194f12d8c start_wqthread + 0


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000000000004   x5: 0x0000000000002820   x6: 0x0000000000000000   x7: 0x0000000000000003
    x8: 0x1d1af99466c32eee   x9: 0x1d1af99589394e6e  x10: 0x00007a8108a30000  x11: 0x00006000022c8000
   x12: 0x0000000000000030  x13: 0x00000000001ff800  x14: 0x00000000000007fb  x15: 0x000000009403b0d7
   x16: 0x0000000000000148  x17: 0x00000001f4acb928  x18: 0x0000000000000000  x19: 0x0000000000000006
   x20: 0x00000001effa6080  x21: 0x0000000000000103  x22: 0x00000001effa6160  x23: 0x00006000018b6700
   x24: 0x00006000018b6700  x25: 0x000000013f20c3e0  x26: 0x000000013f20c400  x27: 0x000000010255d000
   x28: 0x00000001effe6130   fp: 0x000000016daa3e30   lr: 0x0000000194f17c28
    sp: 0x000000016daa3e10   pc: 0x0000000194ee0744 cpsr: 0x40001000
   far: 0x0000000000000000  esr: 0x56000080  Address size fault

Binary Images:
       0x102358000 -        0x102553fff com.noctuasoftware.goxel (0.11.0) <35c87ba0-fb64-3fd9-a03c-fa50f222736b> /Applications/goxel.app/Contents/MacOS/goxel
       0x105a68000 -        0x105a73fff libobjc-trampolines.dylib (*) <106e99a0-0b8d-34fb-ad61-91eca3d8285c> /usr/lib/libobjc-trampolines.dylib
       0x10d114000 -        0x10d17ffff com.apple.AppleMetalOpenGLRenderer (1.0) <76243a19-d6d2-32ee-84d3-7bcfce93d66e> /System/Library/Extensions/AppleMetalOpenGLRenderer.bundle/Contents/MacOS/AppleMetalOpenGLRenderer
       0x194ed7000 -        0x194f10fe7 libsystem_kernel.dylib (*) <a57217d4-b72e-3092-a6e4-3d9c1885fe92> /usr/lib/system/libsystem_kernel.dylib
       0x194f11000 -        0x194f1dfff libsystem_pthread.dylib (*) <1f30fb9a-bdf9-32db-a709-8417666a7e45> /usr/lib/system/libsystem_pthread.dylib
       0x194daf000 -        0x194e2dff7 libsystem_c.dylib (*) <840fe68c-8175-347b-bfb1-3b6bce431935> /usr/lib/system/libsystem_c.dylib
       0x1a3c33000 -        0x1a416bfff libswiftCore.dylib (*) <eaa43988-4f04-3d39-a0a6-d597e46e966e> /usr/lib/swift/libswiftCore.dylib
       0x1981e2000 -        0x1990f1fff com.apple.AppKit (6.9) <ab4a163e-3a53-3fde-a88d-130759291adb> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x195f11000 -        0x1968d6fff com.apple.Foundation (6.9) <19a4dcb2-d426-3efa-80e2-c7a5e1522f64> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
       0x194f77000 -        0x195450fff com.apple.CoreFoundation (6.9) <982f755b-2044-397a-8823-57ddc4341cf3> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x19e816000 -        0x19eb49fff com.apple.HIToolbox (2.1.1) <9bed5c79-f02f-3e0b-9fdb-57d955cc68ba> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
       0x194bba000 -        0x194c48587 dyld (*) <49204446-242b-3d1e-9704-32f8ac99723e> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.2G resident=0K(0%) swapped_out_or_unallocated=1.2G(100%)
Writable regions: Total=3.3G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=3.3G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               256K        2 
Activity Tracing                   256K        1 
CG backing stores                 2176K        4 
CG image                           640K       27 
ColorSync                          576K       29 
CoreAnimation                      256K       16 
CoreGraphics                        32K        2 
CoreGraphics (reserved)             32K        2         reserved VM address space (unallocated)
CoreUI image data                 1424K       12 
Foundation                          32K        2 
Kernel Alloc Once                   32K        1 
MALLOC                           384.9M      111 
MALLOC guard page                  192K       10 
MALLOC_MEDIUM (reserved)         952.0M        8         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
OpenGL GLSL                        256K        3 
STACK GUARD                       56.1M        8 
Stack                             11.7M        8 
VM_ALLOCATE                        1.6G    19099 
__AUTH                            1447K      301 
__AUTH_CONST                      21.5M      509 
__CTF                               824        1 
__DATA                            7430K      497 
__DATA_CONST                      24.0M      514 
__DATA_DIRTY                      1502K      174 
__FONT_DATA                        2352        1 
__GLSLBUILTINS                    5174K        1 
__INFO_FILTER                         8        1 
__LINKEDIT                       802.5M        4 
__OBJC_RO                         66.4M        1 
__OBJC_RW                         2012K        1 
__TEXT                           448.2M      532 
dyld private memory                272K        2 
mapped file                      187.9M       33 
shared memory                      944K       18 
===========                     =======  ======= 
TOTAL                              4.9G    21936 
TOTAL, minus reserved VM space     3.6G    21936 



-----------
Full Report
-----------

{"app_name":"goxel","timestamp":"2024-01-04 17:31:57.00 +0100","app_version":"0.11.0","slice_uuid":"35c87ba0-fb64-3fd9-a03c-fa50f222736b","build_version":"7","platform":1,"bundleID":"com.noctuasoftware.goxel","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.6.1 (22G313)","roots_installed":0,"name":"goxel","incident_id":"2DACE36B-D310-49A9-8A83-C62EAAB153EB"}
{
  "uptime" : 44000,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookAir10,1",
  "coalitionID" : 1492,
  "osVersion" : {
    "train" : "macOS 13.6.1",
    "build" : "22G313",
    "releaseType" : "User"
  },
  "captureTime" : "2024-01-04 17:31:55.1142 +0100",
  "incident" : "2DACE36B-D310-49A9-8A83-C62EAAB153EB",
  "pid" : 4632,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2024-01-04 17:10:29.8694 +0100",
  "procStartAbsTime" : 1046510078306,
  "procExitAbsTime" : 1072270047021,
  "procName" : "goxel",
  "procPath" : "\/Applications\/goxel.app\/Contents\/MacOS\/goxel",
  "bundleInfo" : {"CFBundleShortVersionString":"0.11.0","CFBundleVersion":"7","CFBundleIdentifier":"com.noctuasoftware.goxel"},
  "storeInfo" : {"deviceIdentifierForVendor":"635090A2-AB64-5868-A538-6EB0883C3005","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.noctuasoftware.goxel",
  "crashReporterKey" : "42C6F70A-C4A9-D0A6-7443-B33C6002CDB8",
  "codeSigningID" : "com.noctuasoftware.goxel",
  "codeSigningTeamID" : "VH4XTANA7R",
  "codeSigningFlags" : 570503953,
  "codeSigningValidationCategory" : 6,
  "codeSigningTrustLevel" : 0,
  "wakeTime" : 850,
  "sleepWakeUUID" : "4E52C856-3F20-4130-ABCD-210F19769DB2",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"flags":0,"code":6,"namespace":"SIGNAL","indicator":"Abort trap: 6","byProc":"goxel","byPid":4632},
  "ktriageinfo" : "VM - (arg = 0x0) pmap_enter retried due to resource shortage\nVM - (arg = 0x0) pmap_enter retried due to resource shortage\nVM - (arg = 0x0) pmap_enter retried due to resource shortage\nVM - (arg = 0x0) pmap_enter retried due to resource shortage\nVM - (arg = 0x0) pmap_enter retried due to resource shortage\n",
  "asi" : {"libsystem_c.dylib":["abort() called"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":282330,"threadState":{"x":[{"value":0},{"value":0},{"value":0},{"value":0},{"value":4},{"value":10272},{"value":0},{"value":3},{"value":2097262992268930798},{"value":2097262997142064750},{"value":134694614269952},{"value":105553152737280},{"value":48},{"value":2095104},{"value":2043},{"value":2483269847},{"value":328},{"value":8399927592},{"value":0},{"value":6},{"value":8321130624,"symbolLocation":0,"symbol":"_main_thread"},{"value":259},{"value":8321130848,"symbolLocation":224,"symbol":"_main_thread"},{"value":105553142179584},{"value":105553142179584},{"value":5354079200},{"value":5354079232},{"value":4334145536},{"value":8321392944,"symbolLocation":0,"symbol":"OBJC_CLASS_$_NSApplication"}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6793821224},"cpsr":{"value":1073745920},"fp":{"value":6134840880},"sp":{"value":6134840848},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6793594692,"matchesCrashFrame":1},"far":{"value":0}},"queue":"com.apple.main-thread","frames":[{"imageOffset":38724,"symbol":"__pthread_kill","symbolLocation":8,"imageIndex":3},{"imageOffset":27688,"symbol":"pthread_kill","symbolLocation":288,"imageIndex":4},{"imageOffset":486120,"symbol":"abort","symbolLocation":180,"imageIndex":5},{"imageOffset":3771096,"symbol":"swift::fatalErrorv(unsigned int, char const*, char*)","symbolLocation":136,"imageIndex":6},{"imageOffset":3771128,"symbol":"swift::fatalError(unsigned int, char const*, ...)","symbolLocation":32,"imageIndex":6},{"imageOffset":3772680,"symbol":"swift::runtime::AccessSet::insert(swift::runtime::Access*, void*, void*, swift::ExclusivityFlags)","symbolLocation":536,"imageIndex":6},{"imageOffset":3772780,"symbol":"swift_beginAccess","symbolLocation":84,"imageIndex":6},{"imageOffset":1524816,"imageIndex":0},{"imageOffset":1525824,"imageIndex":0},{"imageOffset":8933268,"symbol":"_routeMouseMovedEvent","symbolLocation":276,"imageIndex":7},{"imageOffset":1469296,"symbol":"-[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:]","symbolLocation":432,"imageIndex":7},{"imageOffset":1468396,"symbol":"-[NSWindow(NSEventRouting) sendEvent:]","symbolLocation":284,"imageIndex":7},{"imageOffset":7194112,"symbol":"routeMouseMovedEvent","symbolLocation":312,"imageIndex":7},{"imageOffset":1464680,"symbol":"-[NSApplication(NSEvent) sendEvent:]","symbolLocation":1100,"imageIndex":7},{"imageOffset":1523948,"imageIndex":0},{"imageOffset":1524080,"imageIndex":0},{"imageOffset":2563084,"symbol":"-[NSApplication _doModalLoop:peek:]","symbolLocation":276,"imageIndex":7},{"imageOffset":2558676,"symbol":"__35-[NSApplication runModalForWindow:]_block_invoke_2","symbolLocation":56,"imageIndex":7},{"imageOffset":2558592,"symbol":"__35-[NSApplication runModalForWindow:]_block_invoke","symbolLocation":108,"imageIndex":7},{"imageOffset":2556772,"symbol":"_NSTryRunModal","symbolLocation":100,"imageIndex":7},{"imageOffset":2556452,"symbol":"-[NSApplication runModalForWindow:]","symbolLocation":292,"imageIndex":7},{"imageOffset":10004152,"symbol":"-[NSSavePanel runModal]","symbolLocation":340,"imageIndex":7},{"imageOffset":252496,"imageIndex":0},{"imageOffset":1174684,"imageIndex":0},{"imageOffset":1495852,"imageIndex":0},{"imageOffset":127868,"imageIndex":0},{"imageOffset":1192672,"imageIndex":0},{"imageOffset":1205932,"imageIndex":0},{"imageOffset":1154344,"imageIndex":0},{"imageOffset":1191136,"imageIndex":0},{"imageOffset":1168096,"imageIndex":0},{"imageOffset":1542180,"imageIndex":0},{"imageOffset":1528468,"imageIndex":0},{"imageOffset":611320,"symbol":"__NSFireTimer","symbolLocation":104,"imageIndex":8},{"imageOffset":627512,"symbol":"__CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__","symbolLocation":32,"imageIndex":9},{"imageOffset":626656,"symbol":"__CFRunLoopDoTimer","symbolLocation":940,"imageIndex":9},{"imageOffset":625464,"symbol":"__CFRunLoopDoTimers","symbolLocation":356,"imageIndex":9},{"imageOffset":516792,"symbol":"__CFRunLoopRun","symbolLocation":1852,"imageIndex":9},{"imageOffset":513064,"symbol":"CFRunLoopRunSpecific","symbolLocation":612,"imageIndex":9},{"imageOffset":200176,"symbol":"RunCurrentEventLoopInMode","symbolLocation":292,"imageIndex":10},{"imageOffset":199724,"symbol":"ReceiveNextEventCommon","symbolLocation":648,"imageIndex":10},{"imageOffset":199044,"symbol":"_BlockUntilNextEventMatchingListInModeWithFilter","symbolLocation":76,"imageIndex":10},{"imageOffset":235900,"symbol":"_DPSNextEvent","symbolLocation":636,"imageIndex":7},{"imageOffset":232216,"symbol":"-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]","symbolLocation":716,"imageIndex":7},{"imageOffset":184188,"symbol":"-[NSApplication run]","symbolLocation":464,"imageIndex":7},{"imageOffset":17356,"symbol":"NSApplicationMain","symbolLocation":880,"imageIndex":7},{"imageOffset":1528852,"imageIndex":0},{"imageOffset":24360,"symbol":"start","symbolLocation":2236,"imageIndex":11}]},{"id":282352,"frames":[{"imageOffset":7564,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":4}]},{"id":282353,"frames":[{"imageOffset":7564,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":4}]},{"id":282389,"frames":[{"imageOffset":7564,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":4}]},{"id":282394,"frames":[{"imageOffset":7564,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":4}]},{"id":282396,"name":"com.apple.NSEventThread","frames":[{"imageOffset":3892,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":3},{"imageOffset":78432,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":3},{"imageOffset":39832,"symbol":"mach_msg_overwrite","symbolLocation":604,"imageIndex":3},{"imageOffset":4784,"symbol":"mach_msg","symbolLocation":24,"imageIndex":3},{"imageOffset":522068,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":9},{"imageOffset":516148,"symbol":"__CFRunLoopRun","symbolLocation":1208,"imageIndex":9},{"imageOffset":513064,"symbol":"CFRunLoopRunSpecific","symbolLocation":612,"imageIndex":9},{"imageOffset":1458004,"symbol":"_NSEventThread","symbolLocation":172,"imageIndex":7},{"imageOffset":28584,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":4},{"imageOffset":7584,"symbol":"thread_start","symbolLocation":8,"imageIndex":4}]},{"id":283374,"frames":[{"imageOffset":7564,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":4}]},{"id":291700,"frames":[{"imageOffset":7564,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":4}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4332027904,
    "CFBundleShortVersionString" : "0.11.0",
    "CFBundleIdentifier" : "com.noctuasoftware.goxel",
    "size" : 2080768,
    "uuid" : "35c87ba0-fb64-3fd9-a03c-fa50f222736b",
    "path" : "\/Applications\/goxel.app\/Contents\/MacOS\/goxel",
    "name" : "goxel",
    "CFBundleVersion" : "7"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4389765120,
    "size" : 49152,
    "uuid" : "106e99a0-0b8d-34fb-ad61-91eca3d8285c",
    "path" : "\/usr\/lib\/libobjc-trampolines.dylib",
    "name" : "libobjc-trampolines.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4514201600,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.AppleMetalOpenGLRenderer",
    "size" : 442368,
    "uuid" : "76243a19-d6d2-32ee-84d3-7bcfce93d66e",
    "path" : "\/System\/Library\/Extensions\/AppleMetalOpenGLRenderer.bundle\/Contents\/MacOS\/AppleMetalOpenGLRenderer",
    "name" : "AppleMetalOpenGLRenderer",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6793555968,
    "size" : 237544,
    "uuid" : "a57217d4-b72e-3092-a6e4-3d9c1885fe92",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6793793536,
    "size" : 53248,
    "uuid" : "1f30fb9a-bdf9-32db-a709-8417666a7e45",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6792343552,
    "size" : 520184,
    "uuid" : "840fe68c-8175-347b-bfb1-3b6bce431935",
    "path" : "\/usr\/lib\/system\/libsystem_c.dylib",
    "name" : "libsystem_c.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7042445312,
    "size" : 5476352,
    "uuid" : "eaa43988-4f04-3d39-a0a6-d597e46e966e",
    "path" : "\/usr\/lib\/swift\/libswiftCore.dylib",
    "name" : "libswiftCore.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6847078400,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15794176,
    "uuid" : "ab4a163e-3a53-3fde-a88d-130759291adb",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2299.70.136"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6810570752,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.Foundation",
    "size" : 10248192,
    "uuid" : "19a4dcb2-d426-3efa-80e2-c7a5e1522f64",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Versions\/C\/Foundation",
    "name" : "Foundation",
    "CFBundleVersion" : "1979.102"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6794211328,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5087232,
    "uuid" : "982f755b-2044-397a-8823-57ddc4341cf3",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1979.102"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6954246144,
    "CFBundleShortVersionString" : "2.1.1",
    "CFBundleIdentifier" : "com.apple.HIToolbox",
    "size" : 3358720,
    "uuid" : "9bed5c79-f02f-3e0b-9fdb-57d955cc68ba",
    "path" : "\/System\/Library\/Frameworks\/Carbon.framework\/Versions\/A\/Frameworks\/HIToolbox.framework\/Versions\/A\/HIToolbox",
    "name" : "HIToolbox"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6790291456,
    "size" : 583048,
    "uuid" : "49204446-242b-3d1e-9704-32f8ac99723e",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 6789627904,
  "size" : 3553509376,
  "uuid" : "531c0369-32b5-3499-ad7a-31d86a6e6b93"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.2G resident=0K(0%) swapped_out_or_unallocated=1.2G(100%)\nWritable regions: Total=3.3G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=3.3G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               256K        2 \nActivity Tracing                   256K        1 \nCG backing stores                 2176K        4 \nCG image                           640K       27 \nColorSync                          576K       29 \nCoreAnimation                      256K       16 \nCoreGraphics                        32K        2 \nCoreGraphics (reserved)             32K        2         reserved VM address space (unallocated)\nCoreUI image data                 1424K       12 \nFoundation                          32K        2 \nKernel Alloc Once                   32K        1 \nMALLOC                           384.9M      111 \nMALLOC guard page                  192K       10 \nMALLOC_MEDIUM (reserved)         952.0M        8         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nOpenGL GLSL                        256K        3 \nSTACK GUARD                       56.1M        8 \nStack                             11.7M        8 \nVM_ALLOCATE                        1.6G    19099 \n__AUTH                            1447K      301 \n__AUTH_CONST                      21.5M      509 \n__CTF                               824        1 \n__DATA                            7430K      497 \n__DATA_CONST                      24.0M      514 \n__DATA_DIRTY                      1502K      174 \n__FONT_DATA                        2352        1 \n__GLSLBUILTINS                    5174K        1 \n__INFO_FILTER                         8        1 \n__LINKEDIT                       802.5M        4 \n__OBJC_RO                         66.4M        1 \n__OBJC_RW                         2012K        1 \n__TEXT                           448.2M      532 \ndyld private memory                272K        2 \nmapped file                      187.9M       33 \nshared memory                      944K       18 \n===========                     =======  ======= \nTOTAL                              4.9G    21936 \nTOTAL, minus reserved VM space     3.6G    21936 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "logWritingSignature" : "8defc70dc9c62909a604c1fc60655116203c6c0d",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "645c2d2f9e69a025b0a37e29",
      "factorPackIds" : {

      },
      "deploymentId" : 240000003
    },
    {
      "rolloutId" : "63508950b3714d3622fc77f7",
      "factorPackIds" : {
        "SIRI_MEMORY_SYNC_CONFIG" : "63508beab3714d3622fc7808"
      },
      "deploymentId" : 240000004
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookAir10,1, BootROM 8422.141.2.700.1, proc 8:4:4 processors, 8 GB, SMC 
Graphics: Apple M1, Apple M1, Built-In
Display: Color LCD, 2560 x 1600 Retina, Main, MirrorOff, Online
Memory Module: LPDDR4, Hynix
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4378), wl0: May 13 2023 07:20:48 version 18.20.383.15.7.8.150 FWID 01-b37727a5
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Air, Apple I

**Comment by JasperMoerland** [comment]
after reinstalling it I get this error -------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               goxel [5055]
Path:                  /private/var/folders/*/goxel.app/Contents/MacOS/goxel
Identifier:            com.noctuasoftware.goxel
Version:               0.11.0 (7)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-01-04 17:46:06.6783 +0100
OS Version:            macOS 13.6.1 (22G313)
Report Version:        12
Anonymous UUID:        42C6F70A-C4A9-D0A6-7443-B33C6002CDB8

Sleep/Wake UUID:       CB110530-F3D8-4518-805C-A11D9B4F9C17

Time Awake Since Boot: 45000 seconds
Time Since Wake:       70 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   goxel [5055]

Application Specific Information:
abort() called


Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x194ee0744 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x194f17c28 pthread_kill + 288
2   libsystem_c.dylib             	       0x194e25ae8 abort + 180
3   libswiftCore.dylib            	       0x1a3fcbad8 swift::fatalErrorv(unsigned int, char const*, char*) + 136
4   libswiftCore.dylib            	       0x1a3fcbaf8 swift::fatalError(unsigned int, char const*, ...) + 32
5   libswiftCore.dylib            	       0x1a3fcc108 swift::runtime::AccessSet::insert(swift::runtime::Access*, void*, void*, swift::ExclusivityFlags) + 536
6   libswiftCore.dylib            	       0x1a3fcc16c swift_beginAccess + 84
7   goxel                         	       0x100858450 0x1006e4000 + 1524816
8   goxel                         	       0x100858840 0x1006e4000 + 1525824
9   AppKit                        	       0x198a66f94 _routeMouseMovedEvent + 276
10  AppKit                        	       0x198348b70 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 432
11  AppKit                        	       0x1983487ec -[NSWindow(NSEventRouting) sendEvent:] + 284
12  AppKit                        	       0x1988be600 routeMouseMovedEvent + 312
13  AppKit                        	       0x198347968 -[NSApplication(NSEvent) sendEvent:] + 1100
14  goxel                         	       0x1008580ec 0x1006e4000 + 1523948
15  goxel                         	       0x100858170 0x1006e4000 + 1524080
16  AppKit                        	       0x198453c0c -[NSApplication _doModalLoop:peek:] + 276
17  AppKit                        	       0x198452ad4 __35-[NSApplication runModalForWindow:]_block_invoke_2 + 56
18  AppKit                        	       0x198452a80 __35-[NSApplication runModalForWindow:]_block_invoke + 108
19  AppKit                        	       0x198452364 _NSTryRunModal + 100
20  AppKit                        	       0x198452224 -[NSApplication runModalForWindow:] + 292
21  AppKit                        	       0x198b6c6b8 -[NSSavePanel runModal] + 340
22  goxel                         	       0x100721a50 0x1006e4000 + 252496
23  goxel                         	       0x100802c9c 0x1006e4000 + 1174684
24  goxel                         	       0x10085132c 0x1006e4000 + 1495852
25  goxel                         	       0x10070337c 0x1006e4000 + 127868
26  goxel                         	       0x1008072e0 0x1006e4000 + 1192672
27  goxel                         	       0x10080a6ac 0x1006e4000 + 1205932
28  goxel                         	       0x1007fdd28 0x1006e4000 + 1154344
29  goxel                         	       0x100806ce0 0x1006e4000 + 1191136
30  goxel                         	       0x1008012e0 0x1006e4000 + 1168096
31  goxel                         	       0x10085c824 0x1006e4000 + 1542180
32  goxel                         	       0x100859294 0x1006e4000 + 1528468
33  Foundation                    	       0x195fa63f8 __NSFireTimer + 104
34  CoreFoundation                	       0x195010338 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
35  CoreFoundation                	       0x19500ffe0 __CFRunLoopDoTimer + 940
36  CoreFoundation                	       0x19500fb38 __CFRunLoopDoTimers + 356
37  CoreFoundation                	       0x194ff52b8 __CFRunLoopRun + 1852
38  CoreFoundation                	       0x194ff4428 CFRunLoopRunSpecific + 612
39  HIToolbox                     	       0x19e846df0 RunCurrentEventLoopInMode + 292
40  HIToolbox                     	       0x19e846c2c ReceiveNextEventCommon + 648
41  HIToolbox                     	       0x19e846984 _BlockUntilNextEventMatchingListInModeWithFilter + 76
42  AppKit                        	       0x19821b97c _DPSNextEvent + 636
43  AppKit                        	       0x19821ab18 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 716
44  AppKit                        	       0x19820ef7c -[NSApplication run] + 464
45  AppKit                        	       0x1981e63cc NSApplicationMain + 880
46  goxel                         	       0x100859414 0x1006e4000 + 1528852
47  dyld                          	       0x194bbff28 start + 2236

Thread 1:
0   libsystem_pthread.dylib       	       0x194f12d8c start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x194f12d8c start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x194f12d8c start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	       0x194f12d8c start_wqthread + 0

Thread 5:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x194ed7f34 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x194eea260 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x194ee0b98 mach_msg_overwrite + 604
3   libsystem_kernel.dylib        	       0x194ed82b0 mach_msg + 24
4   CoreFoundation                	       0x194ff6754 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x194ff5034 __CFRunLoopRun + 1208
6   CoreFoundation                	       0x194ff4428 CFRunLoopRunSpecific + 612
7   AppKit                        	       0x198345f54 _NSEventThread + 172
8   libsystem_pthread.dylib       	       0x194f17fa8 _pthread_start + 148
9   libsystem_pthread.dylib       	       0x194f12da0 thread_start + 8


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000000000005   x5: 0x0000000000000960   x6: 0x0000000000000000   x7: 0x0000000000000003
    x8: 0x91b50204808da751   x9: 0x91b502056f77c7d1  x10: 0x0000ec67f60f0000  x11: 0x0000600003ba4000
   x12: 0x0000000000000030  x13: 0x00000000001ff800  x14: 0x00000000000007fb  x15: 0x00000000fdc1b033
   x16: 0x0000000000000148  x17: 0x00000001f4acb928  x18: 0x0000000000000000  x19: 0x0000000000000006
   x20: 0x00000001effa6080  x21: 0x0000000000000103  x22: 0x00000001effa6160  x23: 0x00006000000bc900
   x24: 0x00006000000bc900  x25: 0x0000000148f0c0f0  x26: 0x0000000148f0c110  x27: 0x00000001008e9000
   x28: 0x00000001effe6130   fp: 0x000000016f717d70   lr: 0x0000000194f17c28
    sp: 0x000000016f717d50   pc: 0x0000000194ee0744 cpsr: 0x40001000
   far: 0x0000000000000000  esr: 0x56000080  Address size fault

Binary Images:
       0x1006e4000 -        0x1008dffff com.noctuasoftware.goxel (0.11.0) <35c87ba0-fb64-3fd9-a03c-fa50f222736b> /private/var/folders/*/goxel.app/Contents/MacOS/goxel
       0x103e28000 -        0x103e33fff libobjc-trampolines.dylib (*) <106e99a0-0b8d-34fb-ad61-91eca3d8285c> /usr/lib/libobjc-trampolines.dylib
       0x10b4d4000 -        0x10b53ffff com.apple.AppleMetalOpenGLRenderer (1.0) <76243a19-d6d2-32ee-84d3-7bcfce93d66e> /System/Library/Extensions/AppleMetalOpenGLRenderer.bundle/Contents/MacOS/AppleMetalOpenGLRenderer
       0x194ed7000 -        0x194f10fe7 libsystem_kernel.dylib (*) <a57217d4-b72e-3092-a6e4-3d9c1885fe92> /usr/lib/system/libsystem_kernel.dylib
       0x194f11000 -        0x194f1dfff libsystem_pthread.dylib (*) <1f30fb9a-bdf9-32db-a709-8417666a7e45> /usr/lib/system/libsystem_pthread.dylib
       0x194daf000 -        0x194e2dff7 libsystem_c.dylib (*) <840fe68c-8175-347b-bfb1-3b6bce431935> /usr/lib/system/libsystem_c.dylib
       0x1a3c33000 -        0x1a416bfff libswiftCore.dylib (*) <eaa43988-4f04-3d39-a0a6-d597e46e966e> /usr/lib/swift/libswiftCore.dylib
       0x1981e2000 -        0x1990f1fff com.apple.AppKit (6.9) <ab4a163e-3a53-3fde-a88d-130759291adb> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x195f11000 -        0x1968d6fff com.apple.Foundation (6.9) <19a4dcb2-d426-3efa-80e2-c7a5e1522f64> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
       0x194f77000 -        0x195450fff com.apple.CoreFoundation (6.9) <982f755b-2044-397a-8823-57ddc4341cf3> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x19e816000 -        0x19eb49fff com.apple.HIToolbox (2.1.1) <9bed5c79-f02f-3e0b-9fdb-57d955cc68ba> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
       0x194bba000 -        0x194c48587 dyld (*) <49204446-242b-3d1e-9704-32f8ac99723e> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)
Writable regions: Total=1.4G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.4G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               128K        1 
Activity Tracing                   256K        1 
CG backing stores                 2176K        4 
CG image                           288K        9 
ColorSync                          512K       25 
CoreAnimation                      176K       11 
CoreGraphics                        32K        2 
CoreServices                       176K        1 
CoreUI image data                 1440K       11 
Foundation                          16K        1 
Kernel Alloc Once                   32K        1 
MALLOC                           264.3M       47 
MALLOC guard page                  192K       10 
MALLOC_MEDIUM (reserved)         720.0M        6         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
OpenGL GLSL                        256K        3 
STACK GUARD                       56.1M        6 
Stack                             10.6M        6 
VM_ALLOCATE                       1056K       36 
__AUTH                             773K      188 
__AUTH_CONST                      13.5M      358 
__CTF                               824        1 
__DATA                            5614K      346 
__DATA_CONST                      15.5M      361 
__DATA_DIRTY                       723K      116 
__FONT_DATA                        2352        1 
__GLSLBUILTINS                    5174K        1 
__LINKEDIT                       802.5M        4 
__OBJC_RO                         66.4M        1 
__OBJC_RW                         2012K        1 
__TEXT                           271.4M      377 
dyld private memory                272K        2 
mapped file                      187.7M       28 
shared memory                     1008K       21 
===========                     =======  ======= 
TOTAL                              2.7G     1988 
TOTAL, minus reserved VM space     1.7G     1988 



-----------
Full Report
-----------

{"app_name":"goxel","timestamp":"2024-01-04 17:46:08.00 +0100","app_version":"0.11.0","slice_uuid":"35c87ba0-fb64-3fd9-a03c-fa50f222736b","build_version":"7","platform":1,"bundleID":"com.noctuasoftware.goxel","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.6.1 (22G313)","roots_installed":0,"name":"goxel","incident_id":"234CA189-D3C0-4A91-9C9A-F541E0529AB4"}
{
  "uptime" : 45000,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookAir10,1",
  "coalitionID" : 3984,
  "osVersion" : {
    "train" : "macOS 13.6.1",
    "build" : "22G313",
    "releaseType" : "User"
  },
  "captureTime" : "2024-01-04 17:46:06.6783 +0100",
  "incident" : "234CA189-D3C0-4A91-9C9A-F541E0529AB4",
  "pid" : 5055,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2024-01-04 17:45:46.1342 +0100",
  "procStartAbsTime" : 1085101373321,
  "procExitAbsTime" : 1085594358741,
  "procName" : "goxel",
  "procPath" : "\/private\/var\/folders\/*\/goxel.app\/Contents\/MacOS\/goxel",
  "bundleInfo" : {"CFBundleShortVersionString":"0.11.0","CFBundleVersion":"7","CFBundleIdentifier":"com.noctuasoftware.goxel"},
  "storeInfo" : {"deviceIdentifierForVendor":"635090A2-AB64-5868-A538-6EB0883C3005","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.noctuasoftware.goxel",
  "crashReporterKey" : "42C6F70A-C4A9-D0A6-7443-B33C6002CDB8",
  "codeSigningID" : "com.noctuasoftware.goxel",
  "codeSigningTeamID" : "VH4XTANA7R",
  "codeSigningFlags" : 570503953,
  "codeSigningValidationCategory" : 6,
  "codeSigningTrustLevel" : 0,
  "wakeTime" : 70,
  "sleepWakeUUID" : "CB110530-F3D8-4518-805C-A11D9B4F9C17",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"flags":0,"code":6,"namespace":"SIGNAL","indicator":"Abort trap: 6","byProc":"goxel","byPid":5055},
  "asi" : {"libsystem_c.dylib":["abort() called"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":298764,"threadState":{"x":[{"value":0},{"value":0},{"value":0},{"value":0},{"value":5},{"value":2400},{"value":0},{"value":3},{"value":10499300324644071249},{"value":10499300328652392401},{"value":259931253964800},{"value":105553178804224},{"value":48},{"value":2095104},{"value":2043},{"value":4257329203},{"value":328},{"value":8399927592},{"value":0},{"value":6},{"value":8321130624,"symbolLocation":0,"symbol":"_main_thread"},{"value":259},{"value":8321130848,"symbolLocation":224,"symbol":"_main_thread"},{"value":105553117038848},{"value":105553117038848},{"value":5518704880},{"value":5518704912},{"value":4304310272},{"value":8321392944,"symbolLocation":0,"symbol":"OBJC_CLASS_$_NSApplication"}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6793821224},"cpsr":{"value":1073745920},"fp":{"value":6164675952},"sp":{"value":6164675920},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6793594692,"matchesCrashFrame":1},"far":{"value":0}},"queue":"com.apple.main-thread","frames":[{"imageOffset":38724,"symbol":"__pthread_kill","symbolLocation":8,"imageIndex":3},{"imageOffset":27688,"symbol":"pthread_kill","symbolLocation":288,"imageIndex":4},{"imageOffset":486120,"symbol":"abort","symbolLocation":180,"imageIndex":5},{"imageOffset":3771096,"symbol":"swift::fatalErrorv(unsigned int, char const*, char*)","symbolLocation":136,"imageIndex":6},{"imageOffset":3771128,"symbol":"swift::fatalError(unsigned int, char const*, ...)","symbolLocation":32,"imageIndex":6},{"imageOffset":3772680,"symbol":"swift::runtime::AccessSet::insert(swift::runtime::Access*, void*, void*, swift::ExclusivityFlags)","symbolLocation":536,"imageIndex":6},{"imageOffset":3772780,"symbol":"swift_beginAccess","symbolLocation":84,"imageIndex":6},{"imageOffset":1524816,"imageIndex":0},{"imageOffset":1525824,"imageIndex":0},{"imageOffset":8933268,"symbol":"_routeMouseMovedEvent","symbolLocation":276,"imageIndex":7},{"imageOffset":1469296,"symbol":"-[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:]","symbolLocation":432,"imageIndex":7},{"imageOffset":1468396,"symbol":"-[NSWindow(NSEventRouting) sendEvent:]","symbolLocation":284,"imageIndex":7},{"imageOffset":7194112,"symbol":"routeMouseMovedEvent","symbolLocation":312,"imageIndex":7},{"imageOffset":1464680,"symbol":"-[NSApplication(NSEvent) sendEvent:]","symbolLocation":1100,"imageIndex":7},{"imageOffset":1523948,"imageIndex":0},{"imageOffset":1524080,"imageIndex":0},{"imageOffset":2563084,"symbol":"-[NSApplication _doModalLoop:peek:]","symbolLocation":276,"imageIndex":7},{"imageOffset":2558676,"symbol":"__35-[NSApplication runModalForWindow:]_block_invoke_2","symbolLocation":56,"imageIndex":7},{"imageOffset":2558592,"symbol":"__35-[NSApplication runModalForWindow:]_block_invoke","symbolLocation":108,"imageIndex":7},{"imageOffset":2556772,"symbol":"_NSTryRunModal","symbolLocation":100,"imageIndex":7},{"imageOffset":2556452,"symbol":"-[NSApplication runModalForWindow:]","symbolLocation":292,"imageIndex":7},{"imageOffset":10004152,"symbol":"-[NSSavePanel runModal]","symbolLocation":340,"imageIndex":7},{"imageOffset":252496,"imageIndex":0},{"imageOffset":1174684,"imageIndex":0},{"imageOffset":1495852,"imageIndex":0},{"imageOffset":127868,"imageIndex":0},{"imageOffset":1192672,"imageIndex":0},{"imageOffset":1205932,"imageIndex":0},{"imageOffset":1154344,"imageIndex":0},{"imageOffset":1191136,"imageIndex":0},{"imageOffset":1168096,"imageIndex":0},{"imageOffset":1542180,"imageIndex":0},{"imageOffset":1528468,"imageIndex":0},{"imageOffset":611320,"symbol":"__NSFireTimer","symbolLocation":104,"imageIndex":8},{"imageOffset":627512,"symbol":"__CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__","symbolLocation":32,"imageIndex":9},{"imageOffset":626656,"symbol":"__CFRunLoopDoTimer","symbolLocation":940,"imageIndex":9},{"imageOffset":625464,"symbol":"__CFRunLoopDoTimers","symbolLocation":356,"imageIndex":9},{"imageOffset":516792,"symbol":"__CFRunLoopRun","symbolLocation":1852,"imageIndex":9},{"imageOffset":513064,"symbol":"CFRunLoopRunSpecific","symbolLocation":612,"imageIndex":9},{"imageOffset":200176,"symbol":"RunCurrentEventLoopInMode","symbolLocation":292,"imageIndex":10},{"imageOffset":199724,"symbol":"ReceiveNextEventCommon","symbolLocation":648,"imageIndex":10},{"imageOffset":199044,"symbol":"_BlockUntilNextEventMatchingListInModeWithFilter","symbolLocation":76,"imageIndex":10},{"imageOffset":235900,"symbol":"_DPSNextEvent","symbolLocation":636,"imageIndex":7},{"imageOffset":232216,"symbol":"-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]","symbolLocation":716,"imageIndex":7},{"imageOffset":184188,"symbol":"-[NSApplication run]","symbolLocation":464,"imageIndex":7},{"imageOffset":17356,"symbol":"NSApplicationMain","symbolLocation":880,"imageIndex":7},{"imageOffset":1528852,"imageIndex":0},{"imageOffset":24360,"symbol":"start","symbolLocation":2236,"imageIndex":11}]},{"id":298779,"frames":[{"imageOffset":7564,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":4}]},{"id":298783,"frames":[{"imageOffset":7564,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":4}]},{"id":298791,"frames":[{"imageOffset":7564,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":4}]},{"id":298792,"frames":[{"imageOffset":7564,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":4}]},{"id":298798,"name":"com.apple.NSEventThread","frames":[{"imageOffset":3892,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":3},{"imageOffset":78432,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":3},{"imageOffset":39832,"symbol":"mach_msg_overwrite","symbolLocation":604,"imageIndex":3},{"imageOffset":4784,"symbol":"mach_msg","symbolLocation":24,"imageIndex":3},{"imageOffset":522068,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":9},{"imageOffset":516148,"symbol":"__CFRunLoopRun","symbolLocation":1208,"imageIndex":9},{"imageOffset":513064,"symbol":"CFRunLoopRunSpecific","symbolLocation":612,"imageIndex":9},{"imageOffset":1458004,"symbol":"_NSEventThread","symbolLocation":172,"imageIndex":7},{"imageOffset":28584,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":4},{"imageOffset":7584,"symbol":"thread_start","symbolLocation":8,"imageIndex":4}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4302192640,
    "CFBundleShortVersionString" : "0.11.0",
    "CFBundleIdentifier" : "com.noctuasoftware.goxel",
    "size" : 2080768,
    "uuid" : "35c87ba0-fb64-3fd9-a03c-fa50f222736b",
    "path" : "\/private\/var\/folders\/*\/goxel.app\/Contents\/MacOS\/goxel",
    "name" : "goxel",
    "CFBundleVersion" : "7"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4360142848,
    "size" : 49152,
    "uuid" : "106e99a0-0b8d-34fb-ad61-91eca3d8285c",
    "path" : "\/usr\/lib\/libobjc-trampolines.dylib",
    "name" : "libobjc-trampolines.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4484579328,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.AppleMetalOpenGLRenderer",
    "size" : 442368,
    "uuid" : "76243a19-d6d2-32ee-84d3-7bcfce93d66e",
    "path" : "\/System\/Library\/Extensions\/AppleMetalOpenGLRenderer.bundle\/Contents\/MacOS\/AppleMetalOpenGLRenderer",
    "name" : "AppleMetalOpenGLRenderer",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6793555968,
    "size" : 237544,
    "uuid" : "a57217d4-b72e-3092-a6e4-3d9c1885fe92",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6793793536,
    "size" : 53248,
    "uuid" : "1f30fb9a-bdf9-32db-a709-8417666a7e45",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6792343552,
    "size" : 520184,
    "uuid" : "840fe68c-8175-347b-bfb1-3b6bce431935",
    "path" : "\/usr\/lib\/system\/libsystem_c.dylib",
    "name" : "libsystem_c.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7042445312,
    "size" : 5476352,
    "uuid" : "eaa43988-4f04-3d39-a0a6-d597e46e966e",
    "path" : "\/usr\/lib\/swift\/libswiftCore.dylib",
    "name" : "libswiftCore.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6847078400,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15794176,
    "uuid" : "ab4a163e-3a53-3fde-a88d-130759291adb",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2299.70.136"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6810570752,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.Foundation",
    "size" : 10248192,
    "uuid" : "19a4dcb2-d426-3efa-80e2-c7a5e1522f64",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Versions\/C\/Foundation",
    "name" : "Foundation",
    "CFBundleVersion" : "1979.102"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6794211328,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5087232,
    "uuid" : "982f755b-2044-397a-8823-57ddc4341cf3",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1979.102"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6954246144,
    "CFBundleShortVersionString" : "2.1.1",
    "CFBundleIdentifier" : "com.apple.HIToolbox",
    "size" : 3358720,
    "uuid" : "9bed5c79-f02f-3e0b-9fdb-57d955cc68ba",
    "path" : "\/System\/Library\/Frameworks\/Carbon.framework\/Versions\/A\/Frameworks\/HIToolbox.framework\/Versions\/A\/HIToolbox",
    "name" : "HIToolbox"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6790291456,
    "size" : 583048,
    "uuid" : "49204446-242b-3d1e-9704-32f8ac99723e",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 6789627904,
  "size" : 3553509376,
  "uuid" : "531c0369-32b5-3499-ad7a-31d86a6e6b93"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)\nWritable regions: Total=1.4G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.4G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               128K        1 \nActivity Tracing                   256K        1 \nCG backing stores                 2176K        4 \nCG image                           288K        9 \nColorSync                          512K       25 \nCoreAnimation                      176K       11 \nCoreGraphics                        32K        2 \nCoreServices                       176K        1 \nCoreUI image data                 1440K       11 \nFoundation                          16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           264.3M       47 \nMALLOC guard page                  192K       10 \nMALLOC_MEDIUM (reserved)         720.0M        6         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nOpenGL GLSL                        256K        3 \nSTACK GUARD                       56.1M        6 \nStack                             10.6M        6 \nVM_ALLOCATE                       1056K       36 \n__AUTH                             773K      188 \n__AUTH_CONST                      13.5M      358 \n__CTF                               824        1 \n__DATA                            5614K      346 \n__DATA_CONST                      15.5M      361 \n__DATA_DIRTY                       723K      116 \n__FONT_DATA                        2352        1 \n__GLSLBUILTINS                    5174K        1 \n__LINKEDIT                       802.5M        4 \n__OBJC_RO                         66.4M        1 \n__OBJC_RW                         2012K        1 \n__TEXT                           271.4M      377 \ndyld private memory                272K        2 \nmapped file                      187.7M       28 \nshared memory                     1008K       21 \n===========                     =======  ======= \nTOTAL                              2.7G     1988 \nTOTAL, minus reserved VM space     1.7G     1988 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "logWritingSignature" : "8defc70dc9c62909a604c1fc60655116203c6c0d",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "645c2d2f9e69a025b0a37e29",
      "factorPackIds" : {

      },
      "deploymentId" : 240000003
    },
    {
      "rolloutId" : "63508950b3714d3622fc77f7",
      "factorPackIds" : {
        "SIRI_MEMORY_SYNC_CONFIG" : "63508beab3714d3622fc7808"
      },
      "deploymentId" : 240000004
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookAir10,1, BootROM 8422.141.2.700.1, proc 8:4:4 processors, 8 GB, SMC 
Graphics: Apple M1, Apple M1, Built-In
Display: Color LCD, 2560 x 1600 Retina, Main, MirrorOff, Online
Memory Module: LPDDR4, Hynix
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4378), wl0: May 13 2023 07:20:48 version 18.20.383.15.7.8.150 FWID 01-b37727a5
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Air, Apple Inc.
Thunderbolt Bus: MacBook Air, Apple Inc.

**Comment by guillaumechereau** [comment]
I cannot reproduce the crash on my Mac.  Can you try with the last build, from here:
https://github.com/guillaumechereau/goxel/actions/runs/7419179426
?
